apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: policy-opa
  namespace: policies
  annotations:
    policy.mcm.ibm.com/categories: >-
      PR.IP Information Protection Processes and Procedures, PR.PT Protective
      Technology
    policy.mcm.ibm.com/controls: 'PR.IP-1 Baseline configuration, PR.PT-3 Least Functionality'
    policy.mcm.ibm.com/standards: NIST-CSF
    seed-generation: '1'
  finalizers:
    - propagator.finalizer.mcm.ibm.com
  generation: 8
spec:
  complianceType: musthave
  remediationAction: enforce   
  disabled: false
  namespaces:
    exclude:
      - kube-*
    include:
      - default
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: opa
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        data:
          no_pod.rego: |-
            package kubernetes.admission
            deny[msg] {
                input.request.kind.kind == "Pod"
                input.request.namespace == "opa"
                image := input.request.object.spec.containers[_].image
                not startswith(image, "hooli.com")
                msg := sprintf("image fails to come from trusted registry: %v", [image])
            }
        kind: ConfigMap
        metadata:
          name: no-pod
          namespace: opa

---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: binding-opa
  namespace: policies
placementRef:
  name: placement-opa
  kind: PlacementPolicy
  apiGroup: mcm.ibm.com
subjects:
- name: policy-opa
  kind: Policy
  apiGroup: policy.mcm.ibm.com

---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-opa
  namespace: policies
spec:
  clusterConditions:
  - type: OK
  clusterSelector:
    matchExpressions:
      []
